AllCops:
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: false
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'municipitaly2.gemspec'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/municipitaly2/search.rb'

Metrics/ParameterLists:
  Max: 10

Style/ClassVars:
  Exclude:
    - 'lib/municipitaly2/data.rb'

Style/CommentedKeyword:
  Exclude:
    - 'lib/municipitaly2/search.rb'
    
